# Generated by Django 4.1.4 on 2022-12-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_address_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='address',
        ),
    ]
