# Generated by Django 4.1.4 on 2022-12-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_location_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='blank-profile-photo.jpg', upload_to='profile_images'),
        ),
    ]
