# Generated by Django 4.1.4 on 2022-12-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
