# Generated by Django 4.1.4 on 2022-12-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='blank-profile-photo.jpg', upload_to='profile_images'),
        ),
    ]
