# Generated by Django 4.1.4 on 2022-12-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_content_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='id_user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
