# Generated by Django 4.1.4 on 2022-12-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='menu_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
