# Generated by Django 4.1.4 on 2022-12-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_content_id_user_alter_content_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
