# Generated by Django 4.1.4 on 2022-12-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content_id',
            field=models.IntegerField(null=True),
        ),
    ]
