# Generated by Django 4.1.4 on 2022-12-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_menu_description_alter_menu_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.DateField(default=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.DateField(default=2022),
        ),
    ]
