# Generated by Django 4.1.4 on 2022-12-16 21:34

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_payment_month_alter_payment_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('type', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('message', models.TextField()),
                ('adminnote', models.TextField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 0, 34, 18, 499592)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 0, 34, 18, 499592)),
        ),
    ]
