# Generated by Django 4.1.4 on 2022-12-16 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_request_alter_payment_month_alter_payment_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 0, 47, 56, 673131)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 0, 47, 56, 673131)),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
