# Generated by Django 4.1.4 on 2022-12-20 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_menu_title_alter_payment_month_alter_payment_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='menu_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 20, 49, 1, 793318)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 20, 49, 1, 793318)),
        ),
    ]
